# -*- coding: utf-8 -*-
"""Image to Pencil Sketch

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDgJurVizwEwAhk0CNjUoktCm-FcCfCr

# **LetsGrowMore**

Name: Satish Kumar

Project Name: Image to Pencil Sketch

Task Level: Beginner 

About: We need to read the image in RBG format and then convert it to a grayscale image. This will turn an image into a classic black and white photo. Then the next thing to do is invert the grayscale image also called negative image, this will be our inverted grayscale image. Inversion can be used to enhance details. Then we can finally create the pencil sketch by mixing the grayscale image with the inverted blurry image. This can be done by dividing the grayscale image by the inverted blurry image. Since images are just arrays, we can easily do this programmatically using the divide function from the cv2 library in Python
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab.patches import cv2_imshow

import cv2
import matplotlib.pyplot as plt

image = cv2.imread('/Nature.jpg')

cv2_imshow(image)
cv2.waitKey(0)

gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray_image)
cv2.waitKey(0)

inverted_image = 255 - gray_image
cv2_imshow(inverted_image)
cv2.waitKey(0)

blurred = cv2.GaussianBlur(inverted_image, (21, 21), 0)
cv2_imshow(blurred)
cv2.waitKey(0)

Inverted_blurred = 255 - blurred
pencil_sketch = cv2.divide(gray_image, inverted_image, scale=256.0)
cv2_imshow(pencil_sketch)
cv2.waitKey(0)

cv2_imshow(image)
cv2_imshow(pencil_sketch)
cv2.waitKey(0)

"""Thank You!!"""